# Generated by Django 5.2.2 on 2025-12-14 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tasks', '0003_remove_task_assigned_to_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_created', 'Task Created'), ('task_due_24h', 'Task Due in 24 Hours'), ('task_due_1h', 'Task Due in 1 Hour'), ('task_overdue', 'Task Overdue')], default='task_created', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskNotificationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_notification_sent', models.BooleanField(default=False)),
                ('due_24h_notification_sent', models.BooleanField(default=False)),
                ('due_1h_notification_sent', models.BooleanField(default=False)),
                ('overdue_notification_sent', models.BooleanField(default=False)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_tracker', to='tasks.task')),
            ],
        ),
    ]
